
spring:
  application:
    name:
      student-management-system
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: adil
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

server:
  port: 8081